leftnav:
- identifier: ede17211-bd49-ea16-6ed7-01f09c1de288
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: dd9a953e-feee-023c-e9f4-e965b7a55d57
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 3f3b7835-cf47-7d3b-a10b-05fbe03cbffa
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 30
- identifier: 6b1f6624-5736-6951-bfe8-5945521b0299
  name: Video Lectures
  url: /video_galleries/video-lectures
  weight: 40
- identifier: 81d6a1cd-707c-29b2-9d65-40b3e79d5433
  name: Readings
  url: /pages/readings
  weight: 50
- identifier: 87609dbb-a9d1-3a6b-234d-62de21a20433
  name: Assignments
  url: /pages/assignments
  weight: 60
- identifier: c13c4766-c0cf-1486-f0cf-6435c531eaad
  name: Exams
  url: /pages/exams
  weight: 70
- identifier: 554b5049-6090-7e6a-e655-66acc1c314b9
  name: Study Materials
  url: /pages/study-materials
  weight: 80
- identifier: b5785e07-1ddb-991c-f3df-d7cc469e6397
  name: Tools
  url: /pages/tools
  weight: 90
- identifier: 6d4babc3-884f-613c-593e-2df8ac802a95
  name: Related Resources
  url: /pages/related-resources
  weight: 100
